services:
  postgres:
    image: postgres:15
    container_name: bidding_db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: